# Copyright (C) 2001-2018, Python Software Foundation
# For licence information, see README file.
#
msgid ""
msgstr ""
"Project-Id-Version: Python 3.7\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2018-11-29 16:06+0100\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: FRENCH <traductions@lists.afpy.org>\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: ../Doc/library/asyncio-exceptions.rst:8
msgid "Exceptions"
msgstr "Exceptions"

#: ../Doc/library/asyncio-exceptions.rst:13
msgid "The operation has exceeded the given deadline."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:16
msgid ""
"This exception is different from the builtin :exc:`TimeoutError` exception."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:22
msgid "The operation has been cancelled."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:24
msgid ""
"This exception can be caught to perform custom operations when asyncio Tasks "
"are cancelled.  In almost all situations the exception must be re-raised."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:30
msgid ""
"This exception is a subclass of :exc:`Exception`, so it can be accidentally "
"suppressed by an overly broad ``try..except`` block::"
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:40
msgid "Instead, the following pattern should be used::"
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:52
msgid "Invalid internal state of :class:`Task` or :class:`Future`."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:54
msgid ""
"Can be raised in situations like setting a result value for a *Future* "
"object that already has a result value set."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:60
msgid ""
"The \"sendfile\" syscall is not available for the given socket or file type."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:63
msgid "A subclass of :exc:`RuntimeError`."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:68
msgid "The requested read operation did not complete fully."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:70
msgid "Raised by the :ref:`asyncio stream APIs<asyncio-streams>`."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:72
msgid "This exception is a subclass of :exc:`EOFError`."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:76
msgid "The total number (:class:`int`) of expected bytes."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:80
msgid "A string of :class:`bytes` read before the end of stream was reached."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:85
msgid "Reached the buffer size limit while looking for a separator."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:87
msgid "Raised by the :ref:`asyncio stream APIs <asyncio-streams>`."
msgstr ""

#: ../Doc/library/asyncio-exceptions.rst:91
msgid "The total number of to be consumed bytes."
msgstr ""
