# Copyright (C) 2001-2018, Python Software Foundation
# For licence information, see README file.
#
msgid ""
msgstr ""
"Project-Id-Version: Python 3\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2020-08-24 09:01+0200\n"
"PO-Revision-Date: 2019-06-10 15:48+0200\n"
"Last-Translator: Dylan Gouin <dygouin@student.42.fr>\n"
"Language-Team: FRENCH <traductions@lists.afpy.org>\n"
"Language: fr\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 2.2\n"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:2
msgid ":mod:`errno` --- Standard errno system symbols"
msgstr ":mod:`errno` — Symboles du système *errno* standard"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:9
msgid ""
"This module makes available standard ``errno`` system symbols. The value of "
"each symbol is the corresponding integer value. The names and descriptions "
"are borrowed from :file:`linux/include/errno.h`, which should be pretty all-"
"inclusive."
msgstr ""
"Ce module met à disposition des symboles du système standard ``errno``. La "
"valeur de chaque symbole est la valeur entière correspondante. Les noms et "
"les descriptions sont empruntés à :file:`linux/include/errno.h`, qui devrait "
"être assez exhaustif."

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:17
msgid ""
"Dictionary providing a mapping from the errno value to the string name in "
"the underlying system.  For instance, ``errno.errorcode[errno.EPERM]`` maps "
"to ``'EPERM'``."
msgstr ""
"Dictionnaire associant la valeur *errno* au nom de chaîne dans le système "
"sous-jacent. Par exemple, ``errno.errorcode[errno.EPERM]`` correspond à "
"``'EPERM'``."

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:21
msgid ""
"To translate a numeric error code to an error message, use :func:`os."
"strerror`."
msgstr ""
"Pour traduire un code d'erreur en message d'erreur, utilisez :func:`os."
"strerror`."

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:23
msgid ""
"Of the following list, symbols that are not used on the current platform are "
"not defined by the module.  The specific list of defined symbols is "
"available as ``errno.errorcode.keys()``.  Symbols available can include:"
msgstr ""
"De la liste suivante, les symboles qui ne sont pas utilisés dans la "
"plateforme actuelle ne sont pas définis par le module. La liste spécifique "
"des symboles définis est disponible comme ``errno.errorcode.keys()``. Les "
"symboles disponibles font partie de cette liste :"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:30
msgid "Operation not permitted"
msgstr "Opération interdite"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:35
msgid "No such file or directory"
msgstr "Fichier ou répertoire inexistant"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:40
msgid "No such process"
msgstr "Processus inexistant"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:45
msgid "Interrupted system call."
msgstr "Appel système interrompu"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:48
msgid "This error is mapped to the exception :exc:`InterruptedError`."
msgstr "Cette erreur est associée à l'exception :exc:`InterruptedError`."

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:53
msgid "I/O error"
msgstr "Erreur d'entrée-sortie"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:58
msgid "No such device or address"
msgstr "Dispositif ou adresse inexistant"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:63
msgid "Arg list too long"
msgstr "Liste d'arguments trop longue"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:68
msgid "Exec format error"
msgstr "Erreur de format d'exécution"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:73
msgid "Bad file number"
msgstr "Mauvais descripteur de fichier"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:78
msgid "No child processes"
msgstr "Pas de processus fils"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:83
msgid "Try again"
msgstr "Ressource temporairement indisponible (réessayez)"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:88
msgid "Out of memory"
msgstr "Mémoire insuffisante"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:93
msgid "Permission denied"
msgstr "Autorisation refusée"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:98
msgid "Bad address"
msgstr "Mauvaise adresse"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:103
msgid "Block device required"
msgstr "Dispositif de bloc requis"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:108
msgid "Device or resource busy"
msgstr "Dispositif ou ressource occupé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:113
msgid "File exists"
msgstr "Fichier déjà existant"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:118
msgid "Cross-device link"
msgstr "Lien inapproprié"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:123
msgid "No such device"
msgstr "Dispositif inexistant"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:128
msgid "Not a directory"
msgstr "Pas un répertoire"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:133
msgid "Is a directory"
msgstr "Est un répertoire"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:138
msgid "Invalid argument"
msgstr "Argument invalide"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:143
msgid "File table overflow"
msgstr "Plus de descripteur de fichier disponible"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:148
msgid "Too many open files"
msgstr "Trop de fichiers ouverts"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:153
msgid "Not a typewriter"
msgstr "Opération de contrôle d'entrée-sortie invalide"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:158
msgid "Text file busy"
msgstr "Fichier texte occupé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:163
msgid "File too large"
msgstr "Fichier trop grand"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:168
msgid "No space left on device"
msgstr "Plus de place sur le dispositif"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:173
msgid "Illegal seek"
msgstr "Recherche invalide"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:178
msgid "Read-only file system"
msgstr "Système de fichiers en lecture seule"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:183
msgid "Too many links"
msgstr "Trop de liens symboliques"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:188
msgid "Broken pipe"
msgstr "Tube brisé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:193
msgid "Math argument out of domain of func"
msgstr "Argument mathématique hors du domaine de définition de la fonction"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:198
msgid "Math result not representable"
msgstr "Résultat mathématique non représentable"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:203
msgid "Resource deadlock would occur"
msgstr "Un interblocage se produirait sur cette ressource"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:208
msgid "File name too long"
msgstr "Nom de fichier trop long"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:213
msgid "No record locks available"
msgstr "Plus de verrou de fichier disponible"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:218
msgid "Function not implemented"
msgstr "Fonction non implémentée"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:223
msgid "Directory not empty"
msgstr "Dossier non vide"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:228
msgid "Too many symbolic links encountered"
msgstr "Trop de liens symboliques trouvés"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:233
msgid "Operation would block"
msgstr "L'opération bloquerait"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:238
msgid "No message of desired type"
msgstr "Pas de message du type voulu"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:243
msgid "Identifier removed"
msgstr "Identifiant supprimé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:248
msgid "Channel number out of range"
msgstr "Le numéro de canal est hors des limites"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:253
msgid "Level 2 not synchronized"
msgstr "Le niveau 2 n'est pas synchronisé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:258
msgid "Level 3 halted"
msgstr "Niveau 3 stoppé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:263
msgid "Level 3 reset"
msgstr "Niveau 3 réinitialisé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:268
msgid "Link number out of range"
msgstr "Le numéro du lien est hors des limites"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:273
msgid "Protocol driver not attached"
msgstr "Le pilote de protocole n'est pas attaché"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:278
msgid "No CSI structure available"
msgstr "Pas de structure *CSI* disponible"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:283
msgid "Level 2 halted"
msgstr "Niveau 2 stoppé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:288
msgid "Invalid exchange"
msgstr "Échange invalide"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:293
msgid "Invalid request descriptor"
msgstr "Descripteur de requête invalide"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:298
msgid "Exchange full"
msgstr "Échange complet"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:303
msgid "No anode"
msgstr "Pas de *anode*"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:308
msgid "Invalid request code"
msgstr "Code de requête invalide"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:313
msgid "Invalid slot"
msgstr "*Slot* invalide"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:318
msgid "File locking deadlock error"
msgstr "Interblocage lors du verrouillage de fichier"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:323
msgid "Bad font file format"
msgstr "Mauvais format de fichier de police"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:328
msgid "Device not a stream"
msgstr "Le périphérique n'est pas un flux"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:333
msgid "No data available"
msgstr "Pas de donnée disponible"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:338
msgid "Timer expired"
msgstr "Délai maximal atteint"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:343
msgid "Out of streams resources"
msgstr "Pas assez de ressources de type flux"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:348
msgid "Machine is not on the network"
msgstr "Machine hors réseau"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:353
msgid "Package not installed"
msgstr "Paquet non installé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:358
msgid "Object is remote"
msgstr "L'objet est distant"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:363
msgid "Link has been severed"
msgstr "Lien coupé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:368
msgid "Advertise error"
msgstr "Erreur d'annonce"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:373
msgid "Srmount error"
msgstr "Erreur *Srmount*"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:378
msgid "Communication error on send"
msgstr "Erreur de communication lors de l'envoi"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:383
msgid "Protocol error"
msgstr "Erreur de protocole"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:388
msgid "Multihop attempted"
msgstr "Transfert à sauts multiples essayé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:393
msgid "RFS specific error"
msgstr "erreur spécifique *RFS*"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:398
msgid "Not a data message"
msgstr "Pas un message de données"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:403
msgid "Value too large for defined data type"
msgstr "Valeur trop grande pour être stockée dans ce type de donnée"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:408
msgid "Name not unique on network"
msgstr "Nom non-unique dans le réseau"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:413
msgid "File descriptor in bad state"
msgstr "Descripteur de fichier en mauvais état"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:418
msgid "Remote address changed"
msgstr "Adresse distante changée"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:423
msgid "Can not access a needed shared library"
msgstr "Accès impossible à une bibliothèque partagée nécessaire"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:428
msgid "Accessing a corrupted shared library"
msgstr "Accès à une bibliothèque partagée corrompue"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:433
msgid ".lib section in a.out corrupted"
msgstr "Section *.lib* de *a.out* corrompue"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:438
msgid "Attempting to link in too many shared libraries"
msgstr "Tentative de liaison entre trop de bibliothèques partagées"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:443
msgid "Cannot exec a shared library directly"
msgstr "Impossible d'exécuter directement une bibliothèque partagée"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:448
msgid "Illegal byte sequence"
msgstr "Séquence de *bytes* illégale"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:453
msgid "Interrupted system call should be restarted"
msgstr "Appel système interrompu qui devrait être relancé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:458
msgid "Streams pipe error"
msgstr "Erreur d’enchaînement de flux"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:463
msgid "Too many users"
msgstr "Trop d'utilisateurs"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:468
msgid "Socket operation on non-socket"
msgstr ""
"Opération d'interface de connexion alors que ce n'est pas une interface de "
"connexion"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:473
msgid "Destination address required"
msgstr "Adresse de destination obligatoire"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:478
msgid "Message too long"
msgstr "Message trop long"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:483
msgid "Protocol wrong type for socket"
msgstr "Mauvais type de protocole pour ce connecteur"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:488
msgid "Protocol not available"
msgstr "Protocole pas disponible"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:493
msgid "Protocol not supported"
msgstr "Protocole non géré"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:498
msgid "Socket type not supported"
msgstr "Type de connecteur non géré"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:503
msgid "Operation not supported on transport endpoint"
msgstr "Opération non gérée par cette fin de lien"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:508
msgid "Protocol family not supported"
msgstr "Famille de protocole non gérée"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:513
msgid "Address family not supported by protocol"
msgstr "Famille d'adresses non gérée par ce protocole"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:518
msgid "Address already in use"
msgstr "Adresse déjà utilisée"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:523
msgid "Cannot assign requested address"
msgstr "Impossible d'assigner l'adresse demandée"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:528
msgid "Network is down"
msgstr "Le réseau est désactivé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:533
msgid "Network is unreachable"
msgstr "Réseau inaccessible"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:538
msgid "Network dropped connection because of reset"
msgstr "Connexion annulée par le réseau"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:543
msgid "Software caused connection abort"
msgstr "Connexion abandonnée"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:548
msgid "Connection reset by peer"
msgstr "Connexion réinitialisée"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:553
msgid "No buffer space available"
msgstr "Plus d'espace tampon disponible"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:558
msgid "Transport endpoint is already connected"
msgstr "L'interface de connexion est déjà connectée"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:563
msgid "Transport endpoint is not connected"
msgstr "L'interface de connexion n'est pas connectée"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:568
msgid "Cannot send after transport endpoint shutdown"
msgstr "Impossible d'envoyer après l'arrêt du point final du transport"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:573
msgid "Too many references: cannot splice"
msgstr "Trop de descripteurs : impossible d'effectuer la liaison"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:578
msgid "Connection timed out"
msgstr "Délai maximal de connexion écoulé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:583
msgid "Connection refused"
msgstr "Connexion refusée"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:588
msgid "Host is down"
msgstr "Hôte éteint"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:593
msgid "No route to host"
msgstr "Pas de route vers l'hôte"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:598
msgid "Operation already in progress"
msgstr "Connexion déjà en cours"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:603
msgid "Operation now in progress"
msgstr "Opération en cours"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:608
msgid "Stale NFS file handle"
msgstr "Descripteur de fichier NFS corrompu"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:613
msgid "Structure needs cleaning"
msgstr "La structure a besoin d'être nettoyée"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:618
msgid "Not a XENIX named type file"
msgstr "N'est pas un fichier nommé du type *XENIX*"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:623
msgid "No XENIX semaphores available"
msgstr "Pas de sémaphore *XENIX* disponible"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:628
msgid "Is a named type file"
msgstr "Est un fichier nommé"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:633
msgid "Remote I/O error"
msgstr "Erreur d'entrées-sorties distante"

#: /Users/seluj78/Projects/python-docs-fr/venv/worktrees/3.9/Doc/library/errno.rst:638
msgid "Quota exceeded"
msgstr "Quota dépassé"
